USE [shawn_db]
GO

/****** Object:  Table [dbo].[RAINBOW_{0}]    Script Date: 11/7/2017 11:28:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RAINBOW_{0}](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Word] [varchar](255) NOT NULL,
	[FirstLetter] [varchar](1) NOT NULL,
	[LetterCount] [int] NOT NULL,
	[MD5] [varchar](255) NULL,
	[SHA] [varchar](255) NULL,
	[SHA1] [varchar](255) NULL,
	[SHA2_256] [varchar](255) NULL,
	[SHA2_512] [varchar](255) NULL,
 CONSTRAINT [PK_RAINBOW_{0}] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

SET ANSI_PADDING ON

GO

/****** Object:  Index [IX_FIRSTLETTER_{0}]    Script Date: 11/7/2017 11:28:43 AM ******/
CREATE NONCLUSTERED INDEX [IX_FIRSTLETTER_{0}] ON [dbo].[RAINBOW_{0}]
(
	[FirstLetter] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_LETTERCOUNT_{0}]    Script Date: 11/7/2017 11:28:43 AM ******/
CREATE NONCLUSTERED INDEX [IX_LETTERCOUNT_{0}] ON [dbo].[RAINBOW_{0}]
(
	[LetterCount] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON

GO

/****** Object:  Index [IX_MD5_{0}]    Script Date: 11/7/2017 11:28:43 AM ******/
CREATE NONCLUSTERED INDEX [IX_MD5_{0}] ON [dbo].[RAINBOW_{0}]
(
	[MD5] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON

GO

/****** Object:  Index [IX_SHA_{0}]    Script Date: 11/7/2017 11:28:43 AM ******/
CREATE NONCLUSTERED INDEX [IX_SHA_{0}] ON [dbo].[RAINBOW_{0}]
(
	[SHA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON

GO

/****** Object:  Index [IX_SHA1_{0}]    Script Date: 11/7/2017 11:28:43 AM ******/
CREATE NONCLUSTERED INDEX [IX_SHA1_{0}] ON [dbo].[RAINBOW_{0}]
(
	[SHA1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON

GO

/****** Object:  Index [IX_SHA2_256_{0}]    Script Date: 11/7/2017 11:28:43 AM ******/
CREATE NONCLUSTERED INDEX [IX_SHA2_256_{0}] ON [dbo].[RAINBOW_{0}]
(
	[SHA2_256] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON

GO

/****** Object:  Index [IX_SHA2_512_{0}]    Script Date: 11/7/2017 11:28:43 AM ******/
CREATE NONCLUSTERED INDEX [IX_SHA2_512_{0}] ON [dbo].[RAINBOW_{0}]
(
	[SHA2_512] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON

GO

/****** Object:  Index [IX_WORD_{0}]    Script Date: 11/7/2017 11:28:43 AM ******/
CREATE NONCLUSTERED INDEX [IX_WORD_{0}] ON [dbo].[RAINBOW_{0}]
(
	[Word] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


